autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    max_inner_loop_ratio: 0.2
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.90
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 90
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 32
    batch_size_test: 512
    cv_valid_ratio: 0.2
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
#    max_size: 64
    max_times: 3
    max_valid_count: 512
    steps_per_epoch: 30
    train_info_sample: 256
  optimizer:
    lr: 0.025
