active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    max_inner_loop_ratio: 0.16060631266342637
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.9070530812132992
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 70
    test_after_at_least_seconds_step: 10
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.00015391256444204055
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 18
    batch_size_test: 256
    cv_valid_ratio: 0.08064040373201792
    enough_count:
      image: 57361
      video: 496
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 4
    max_valid_count: 143
    steps_per_epoch: 53
    train_info_sample: 187
  optimizer:
    lr: 0.04905662642879468
    min_lr: 3.4021903328283246e-08
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
