active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.10914069248829486
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.8107690403967625
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 90
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0011068585344639434
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 20
    batch_size_test: 256
    cv_valid_ratio: 0.12308250624143527
    enough_count:
      image: 9981
      video: 3576
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 9
    max_valid_count: 254
    steps_per_epoch: 8
    train_info_sample: 304
  optimizer:
    lr: 0.00920103492069028
    min_lr: 1.2148907843987434e-08
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
