autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    first_simple_model: false
    max_inner_loop_ratio: 0.21334602174504314
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.8592446961363361
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 71
    test_after_at_least_seconds_step: 3
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
    use_test_ensemble: true
  dataset:
    base: 16
    batch_size: 45
    batch_size_test: 256
    cv_valid_ratio: 0.09066743341914285
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 128
    max_times: 8
    max_valid_count: 161
    steps_per_epoch: 32
    train_info_sample: 183
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.30000000000000004
    lr: 0.0021547966589593134
    min_lr: 3.368294059811878e-06
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 4
    warmup_multiplier: 3.0
    wd: 0.00026231073839497594