active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    first_simple_model: false
    max_inner_loop_ratio: 0.1454569596170737
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.7087074735078951
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 100
    test_after_at_least_seconds_step: 8
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 19
    batch_size_test: 256
    cv_valid_ratio: 0.16622066063526897
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 128
    max_times: 8
    max_valid_count: 151
    steps_per_epoch: 202
    train_info_sample: 417
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.30000000000000004
    lr: 0.001724571524920099
    min_lr: 5.766760649033205e-07
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: AdamW
    warm_up_epoch: 5
    warmup_multiplier: 2.0
    wd: 0.002679607626376864
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
