active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    first_simple_model: false
    max_inner_loop_ratio: 0.24177316154515952
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.8414556314492518
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 79
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 60
    batch_size_test: 256
    cv_valid_ratio: 0.15261820273200563
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 455
    steps_per_epoch: 143
    train_info_sample: 140
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.2
    lr: 0.01182619670458885
    min_lr: 1.9538411687103383e-07
    momentum: 0.011218154954900786
    nesterov: true
    scheduler: cosine
    type: SGD
    warm_up_epoch: 4
    warmup_multiplier: 1.5
    wd: 0.00983365273030235
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
