# Dataset: Chucky
# DeepWisdom + hyperparams from AutoML-Freiburg
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    first_simple_model: true
    max_inner_loop_ratio: 0.2662288711682015
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.7467089085430769
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 118
    test_after_at_least_seconds_step: 7
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
    # add ensemble option from DeepBlueAI
    use_test_ensemble: false
  dataset:
    base: 16
    batch_size: 28
    batch_size_test: 256
    cv_valid_ratio: 0.1764234801857658
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 401
    steps_per_epoch: 163
    train_info_sample: 254
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.30000000000000004
    lr: 0.000629745503256168
    min_lr: 4.938870859796894e-07
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: AdamW
    warm_up_epoch: 5
    warmup_multiplier: 2.0
    wd: 0.0028826154281075254
