active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    first_simple_model: true
    max_inner_loop_ratio: 0.2783907252218899
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.8192213013975004
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 116
    test_after_at_least_seconds_step: 7
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 49
    batch_size_test: 256
    cv_valid_ratio: 0.11554031214778594
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 32
    max_times: 8
    max_valid_count: 159
    steps_per_epoch: 6
    train_info_sample: 319
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.2
    lr: 0.000739406420485375
    min_lr: 1.213957463150511e-06
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: Adam
    warm_up_epoch: 6
    warmup_multiplier: 1.5
    wd: 0.002190338580230704
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
