active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    first_simple_model: false
    max_inner_loop_ratio: 0.24266678678491113
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.8783643757623363
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 75
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 18
    batch_size_test: 256
    cv_valid_ratio: 0.058480784113292064
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 128
    max_times: 8
    max_valid_count: 387
    steps_per_epoch: 7
    train_info_sample: 229
  model:
    architecture: efficientnetb1
  optimizer:
    amsgrad: true
    freeze_portion: 0.5
    lr: 0.004003635359488426
    min_lr: 7.56487588854217e-07
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 6
    warmup_multiplier: 2.5
    wd: 0.00019419995769886616
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
