active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    first_simple_model: false
    max_inner_loop_ratio: 0.29440949496701674
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.9224716550358871
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 67
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 42
    batch_size_test: 256
    cv_valid_ratio: 0.13843557938367823
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 379
    steps_per_epoch: 31
    train_info_sample: 368
  model:
    architecture: efficientnetb1
  optimizer:
    amsgrad: false
    freeze_portion: 0.2
    lr: 0.08356247187146085
    min_lr: 1.191935060622313e-07
    momentum: 0.7909321658226259
    nesterov: false
    scheduler: plateau
    type: SGD
    warm_up_epoch: 6
    warmup_multiplier: 3.0
    wd: 1.627734853442257e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
