# Codalab submission
extra_packages: []  # Paths
active_model_files: []  # With respect to model_dir

autonlp:
  common:
    max_vocab_size: 20000   # maximum number of vocabulary to be embedded, must be larger than number of different words in the dataset
    max_char_length: 96     # maximum number of characters for chinese samples
    max_seq_length: 301     # maximum sequence length for non chinese samples

  model:
    num_epoch: 1              # number of epochs to train the classifier
    total_call_num: 20        # how often the test function shall be called
    valid_ratio: 0.1          # train/validation split ratio
    increase_batch_acc: 0.65  # batch size will be increased below this accuracy
    early_stop_auc: 0.8       # minimum auc for an early stop
    init_batch_size: 32       # guess what
    ft_dir: ['/app/embedding',
             '/home/ferreira/autodl_data/embedding',
             '/home/dingsda/data/embedding']  # paths to look for the embedding model

  data_manager:
    chi_word_length: 2
    max_valid_perclass_sample: 400
    max_sample_train: 18000
    max_train_perclass_sample: 800

  model_manager:
    embedding_dim: 300      # word embedding size

  optimizer:
    lr: 0.001
    rho: 0.1                # actually the parameter is 1-rho. But this way the config space can be described more easily

autospeech:
  common:
    model_first_max_run_loop: 3
    max_audio_duration: 5           # original comment: limited length of audio, like 20s
    first_round_duration: 10
    middle_duration: 15
    second_round_duration: 30
    audio_sample_rate: 16000
    max_frame_num: 700
    is_cut_audio: True
    num_mfcc: 96                    # original comment: num of mfcc features, default value is 24
    sr: 16000
    fft_duration: 0.1
    hop_duration: 0.04

  data_manager:
    max_valid_perclass_sample: 200
    min_valid_per_class: 1

  optimizer:
    lr_attention_gru: !!float 1e-3
    lr_bilstm_attention: !!float 1e-3
    lr_crnn: !!float 1e-3
    lr_crnn2d: !!float 1e-3
    lr_crnn2d_larger: !!float 1e-3
    lr_crnn2d_vgg: !!float 1e-3
    lr_lstm_attention: !!float 1e-3

    beta_1: 0.9             # actually the parameter is 1-beta_1. But this way the config space can be described more easily
    beta_2: 0.999           # actually the parameter is 1-beta_2. But this way the config space can be described more easily
    epsilon: !!float 1e-08
    decay: !!float 1e-4
    schedule_decay: 0.004
    amsgrad: True




