active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    max_inner_loop_ratio: 0.21282717788804667
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.7127346079300021
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 81
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.00025015476050381806
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 50
    batch_size_test: 256
    cv_valid_ratio: 0.16481328651224036
    enough_count:
      image: 1776
      video: 149
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 236
    steps_per_epoch: 19
    train_info_sample: 180
  optimizer:
    lr: 0.015105671602995013
    min_lr: 1.2261841010659892e-06
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
