active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.28221412943247326
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.7154837926377792
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 99
    test_after_at_least_seconds_step: 4
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0006075101013955718
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 19
    batch_size_test: 256
    cv_valid_ratio: 0.15380589149790078
    enough_count:
      image: 11430
      video: 111
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 10
    max_valid_count: 247
    steps_per_epoch: 72
    train_info_sample: 451
  optimizer:
    lr: 0.02579142997568237
    min_lr: 3.753177947123999e-08
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
