active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    max_inner_loop_ratio: 0.10998284829603398
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.7252394845227197
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 96
    test_after_at_least_seconds_step: 7
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0005918534488949854
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 60
    batch_size_test: 256
    cv_valid_ratio: 0.17263409698853427
    enough_count:
      image: 1805
      video: 226
    log2_max_size: 128
    max_epoch: 1000
    max_size: 64
    max_times: 7
    max_valid_count: 449
    steps_per_epoch: 5
    train_info_sample: 169
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.0
    lr: 0.0006076961220943537
    min_lr: 3.393192498213659e-06
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 4
    warmup_multiplier: 1.0
    wd: 3.507705384873711e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
