active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    max_inner_loop_ratio: 0.13263590080594348
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.7088425650548011
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 93
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.004982228281678852
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 61
    batch_size_test: 256
    cv_valid_ratio: 0.10728049219413928
    enough_count:
      image: 6588
      video: 1139
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 6
    max_valid_count: 454
    steps_per_epoch: 17
    train_info_sample: 492
  model:
    architecture: efficientnetb1
  optimizer:
    amsgrad: false
    freeze_portion: 0.4
    lr: 9.966914111531283e-05
    min_lr: 8.36673777505742e-06
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: Adam
    warm_up_epoch: 3
    warmup_multiplier: 2.5
    wd: 3.6981852684904534e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
