active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    max_inner_loop_ratio: 0.10560208169324854
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.9212829785572023
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 66
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001171198592344215
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 55
    batch_size_test: 256
    cv_valid_ratio: 0.0588812523578521
    enough_count:
      image: 8720
      video: 129
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 6
    max_valid_count: 158
    steps_per_epoch: 21
    train_info_sample: 153
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.4
    lr: 0.09820100431021266
    min_lr: 3.570560838995442e-08
    momentum: 0.309209100605906
    nesterov: false
    scheduler: cosine
    type: SGD
    warm_up_epoch: 6
    warmup_multiplier: 2.5
    wd: 1.6197875353111547e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
