active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.23681700892466148
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.8338371621596925
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 82
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0006840309379199311
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 27
    batch_size_test: 256
    cv_valid_ratio: 0.1310599866910743
    enough_count:
      image: 4868
      video: 1313
    log2_max_size: 128
    max_epoch: 1000
    max_size: 64
    max_times: 9
    max_valid_count: 131
    steps_per_epoch: 20
    train_info_sample: 319
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.1
    lr: 0.0002364031215391623
    min_lr: 2.22016064205813e-06
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: Adam
    warm_up_epoch: 5
    warmup_multiplier: 2.0
    wd: 0.0002720819988630764
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
