active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.23516098026942128
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.8007846070729789
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 106
    test_after_at_least_seconds_step: 4
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0005058566697341702
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 27
    batch_size_test: 256
    cv_valid_ratio: 0.16831385397453705
    enough_count:
      image: 47620
      video: 1400
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 9
    max_valid_count: 138
    steps_per_epoch: 27
    train_info_sample: 138
  optimizer:
    lr: 0.006356127164198591
    min_lr: 7.091182440062478e-06
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
