active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.2693449125945482
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.9257803794640967
    test_after_at_least_seconds: 1
    test_after_at_least_seconds_max: 74
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0007430527197204669
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 34
    batch_size_test: 256
    cv_valid_ratio: 0.07159151682637199
    enough_count:
      image: 1547
      video: 3539
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 4
    max_valid_count: 260
    steps_per_epoch: 6
    train_info_sample: 138
  optimizer:
    lr: 0.021668635545553656
    min_lr: 3.360470587429775e-08
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
