active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.1787962367617681
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.8126253401566343
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 102
    test_after_at_least_seconds_step: 3
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.002967536373422423
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 43
    batch_size_test: 256
    cv_valid_ratio: 0.054645414250737205
    enough_count:
      image: 2453
      video: 4237
    log2_max_size: 128
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 172
    steps_per_epoch: 12
    train_info_sample: 282
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.0
    lr: 0.0009227223490597875
    min_lr: 7.0650572075679904e-06
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: Adam
    warm_up_epoch: 3
    warmup_multiplier: 1.5
    wd: 6.160526950527841e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
