active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    max_inner_loop_ratio: 0.19418208755526495
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.7012736408307044
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 115
    test_after_at_least_seconds_step: 4
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.00010514465202093091
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 36
    batch_size_test: 256
    cv_valid_ratio: 0.14430062644326108
    enough_count:
      image: 23836
      video: 5362
    log2_max_size: 128
    max_epoch: 1000
    max_size: 64
    max_times: 9
    max_valid_count: 356
    steps_per_epoch: 35
    train_info_sample: 487
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.0
    lr: 9.788822732139345e-05
    min_lr: 2.954443671948158e-07
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 6
    warmup_multiplier: 2.0
    wd: 0.007600621710143168
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
