active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.14513304343976152
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.7874660037300345
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 104
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.003705815518801853
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 59
    batch_size_test: 256
    cv_valid_ratio: 0.16194710604224116
    enough_count:
      image: 1571
      video: 1134
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 6
    max_valid_count: 202
    steps_per_epoch: 58
    train_info_sample: 147
  model:
    architecture: efficientnetb0
  optimizer:
    amsgrad: false
    freeze_portion: 0.5
    lr: 0.0002960711758702167
    min_lr: 4.05315846964233e-08
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 5
    warmup_multiplier: 1.5
    wd: 0.004465536949171847
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
