active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.10228740449647385
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.8361569039917136
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 63
    test_after_at_least_seconds_step: 7
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0014198981536204039
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 48
    batch_size_test: 256
    cv_valid_ratio: 0.10538243201532894
    enough_count:
      image: 4946
      video: 137
    log2_max_size: 32
    max_epoch: 1000
    max_size: 64
    max_times: 6
    max_valid_count: 457
    steps_per_epoch: 9
    train_info_sample: 502
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.30000000000000004
    lr: 0.00032977042349006854
    min_lr: 1.659070085004443e-07
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 3
    warmup_multiplier: 2.5
    wd: 0.0007235553866310846
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
