active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    max_inner_loop_ratio: 0.2684716032803817
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    skip_valid_score_threshold: 0.8550881679883294
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 95
    test_after_at_least_seconds_step: 6
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001963010329815128
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 20
    batch_size_test: 256
    cv_valid_ratio: 0.11110474060835263
    enough_count:
      image: 14694
      video: 447
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 10
    max_valid_count: 242
    steps_per_epoch: 146
    train_info_sample: 281
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.2
    lr: 0.0013127851069483286
    min_lr: 1.7426733049444243e-08
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: AdamW
    warm_up_epoch: 4
    warmup_multiplier: 2.5
    wd: 0.00026162366400180666
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
