active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 1
    first_simple_model: true
    max_inner_loop_ratio: 0.24391584550105805
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.8136129538551593
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 72
    test_after_at_least_seconds_step: 7
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 22
    batch_size_test: 256
    cv_valid_ratio: 0.11600674651587474
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 283
    steps_per_epoch: 49
    train_info_sample: 422
  model:
    architecture: efficientnetb1
  optimizer:
    amsgrad: false
    freeze_portion: 0.30000000000000004
    lr: 0.002857654850749139
    min_lr: 4.802545993639309e-08
    momentum: 0.9
    nesterov: true
    scheduler: plateau
    type: Adam
    warm_up_epoch: 6
    warmup_multiplier: 2.5
    wd: 0.0004156378004335563
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
