active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    first_simple_model: false
    max_inner_loop_ratio: 0.10737287419541351
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.7377437369172023
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 63
    test_after_at_least_seconds_step: 10
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 32
    batch_size_test: 256
    cv_valid_ratio: 0.06238989914303163
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 32
    max_times: 8
    max_valid_count: 418
    steps_per_epoch: 82
    train_info_sample: 224
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: false
    freeze_portion: 0.4
    lr: 0.0012432805922987327
    min_lr: 3.7508010525020624e-06
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: AdamW
    warm_up_epoch: 5
    warmup_multiplier: 2.0
    wd: 6.248562894023326e-05
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
