active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    first_simple_model: false
    max_inner_loop_ratio: 0.17269506965506154
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: RF
    skip_valid_score_threshold: 0.7650438778404267
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 102
    test_after_at_least_seconds_step: 9
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 51
    batch_size_test: 256
    cv_valid_ratio: 0.0860389450813345
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 64
    max_times: 8
    max_valid_count: 280
    steps_per_epoch: 52
    train_info_sample: 213
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.30000000000000004
    lr: 0.00041338934160335477
    min_lr: 2.1570669508691376e-08
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: Adam
    warm_up_epoch: 4
    warmup_multiplier: 1.5
    wd: 0.00032432372914421566
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
