active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    first_simple_model: true
    max_inner_loop_ratio: 0.17889506498685126
    min_lr: 1.0e-06
    output_majority_first: false
    score_type: auc
    simple_model: LR
    skip_valid_score_threshold: 0.9178095742833309
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 109
    test_after_at_least_seconds_step: 8
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.001
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 33
    batch_size_test: 256
    cv_valid_ratio: 0.13093972150519312
    enough_count:
      image: 10000
      video: 1000
    max_epoch: 1000
    max_size: 128
    max_times: 8
    max_valid_count: 135
    steps_per_epoch: 73
    train_info_sample: 458
  model:
    architecture: ResNet18
  optimizer:
    amsgrad: true
    freeze_portion: 0.0
    lr: 0.00010932265600469902
    min_lr: 1.7816950647126657e-07
    momentum: 0.9
    nesterov: true
    scheduler: cosine
    type: Adam
    warm_up_epoch: 5
    warmup_multiplier: 1.0
    wd: 0.0004762213011362616
cluster_datasets_dir: /data/aad/image_datasets/augmented_datasets
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
is_submission: false
