active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 2
    max_inner_loop_ratio: 0.17191376397652663
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.8965690955464721
    test_after_at_least_seconds: 2
    test_after_at_least_seconds_max: 117
    test_after_at_least_seconds_step: 6
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.007092407912061495
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 42
    batch_size_test: 256
    cv_valid_ratio: 0.1513632735576806
    enough_count:
      image: 40468
      video: 2635
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 7
    max_valid_count: 457
    steps_per_epoch: 60
    train_info_sample: 279
  optimizer:
    lr: 0.013902022588510551
    min_lr: 2.3293629246862438e-07
cluster_datasets_dir: /data/aad/image_datasets/all_symlinks
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
