active_model_files: []
autocv:
  checkpoints:
    keep: 50
  conditions:
    early_epoch: 3
    max_inner_loop_ratio: 0.1826717751687259
    min_lr: 1.0e-06
    score_type: auc
    skip_valid_score_threshold: 0.8839695241542584
    test_after_at_least_seconds: 3
    test_after_at_least_seconds_max: 107
    test_after_at_least_seconds_step: 2
    threshold_valid_best_score: 0.997
    threshold_valid_score_diff: 0.0006489315256708472
    use_fast_auto_aug: true
  dataset:
    base: 16
    batch_size: 16
    batch_size_test: 256
    cv_valid_ratio: 0.15861384380590718
    enough_count:
      image: 25798
      video: 397
    log2_max_size: 64
    max_epoch: 1000
    max_size: 64
    max_times: 4
    max_valid_count: 147
    steps_per_epoch: 13
    train_info_sample: 353
  optimizer:
    lr: 0.012707514377072616
    min_lr: 1.0048450860784805e-07
cluster_datasets_dir: /data/aad/image_datasets/challenge/
cluster_model_dir: /home/ferreira/autodl_data/models
extra_packages: []
